export const companyAnalysisData = [
  {
    company_name: "20 Microns",
    current_market_price: 198.0,
    company_screener: "https://www.screener.in/company/20MICRONS/consolidated/",
    median_pe: 9.8,
    pe: 11.4,
    company_symbol: "533022",
    company_peers:
      '[{"company_name": "Coal India", "company_screener": "https://www.screener.in/company/COALINDIA/consolidated/"}, {"company_name": "G M D C", "company_screener": "https://www.screener.in/company/GMDCLTD/consolidated/"}, {"company_name": "KIOCL", "company_screener": "https://www.screener.in/company/KIOCL/"}, {"company_name": "Lloyds Metals", "company_screener": "https://www.screener.in/company/LLOYDSME/"}, {"company_name": "MOIL", "company_screener": "https://www.screener.in/company/MOIL/"}, {"company_name": "NMDC", "company_screener": "https://www.screener.in/company/NMDC/consolidated/"}, {"company_name": "Sandur Manganese", "company_screener": "https://www.screener.in/company/SANDUMA/"}, {"company_name": "Vedanta", "company_screener": "https://www.screener.in/company/VEDL/consolidated/"}, {"company_name": "Asi Industries", "company_screener": "https://www.screener.in/company/502015/"}]',
    sector: "Mining & Mineral products",
    industry: "Mining / Minerals / Metals",
    pe_score: 0.01,
    peg_score: 0.4,
    peg_ranking: 5,
    de_score: 0.58,
    de_ranking: 9,
    piotroski: 8,
    piotroski_rank: 1,
    piotroski_score: 1.0,
    daily_filter_score: 10.0,
    sales_growth: "[22.73, 20.27, 20.99, 22.54]",
    sales_rank: "[2, 6, 4, 2]",
    sales_score: 0.41,
    sales_filter_score: 5.5,
    profit_growth: "[18.37, -3.55, 19.79, 46.67]",
    profit_rank: "[5, 7, 5, 1]",
    profit_score: 0.18,
    profit_filter_score: 1.5,
    roe_10y: 14.0,
    roe_5y: 15.0,
    roe_3y: 16.0,
    roe_1y: 18.0,
    roe_rank_10y: 5,
    roe_rank_5y: 6,
    roe_rank_3y: 6,
    roe_rank_1y: 4,
    score: 0.2,
    filter_count: 1,
    total_ranks: 10,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 18.0,
    sum_score: 0.42,
    final_score: 9.16,
    target_price: null,
    Indicator: "Sell",
    SellPrice: null,
  },
  {
    company_name: "3M India",
    current_market_price: 27765.0,
    company_screener: "https://www.screener.in/company/3MINDIA/",
    median_pe: 79.3,
    pe: 56.4,
    company_symbol: "523395",
    company_peers:
      '[{"company_name": "Balmer Lawrie", "company_screener": "https://www.screener.in/company/BALMLAWRIE/consolidated/"}, {"company_name": "Nava", "company_screener": "https://www.screener.in/company/NAVA/consolidated/"}, {"company_name": "Quess Corp", "company_screener": "https://www.screener.in/company/QUESS/consolidated/"}]',
    sector: "Diversified",
    industry: "Diversified - Large",
    pe_score: 1.0,
    peg_score: 0.18,
    peg_ranking: 3,
    de_score: 0.99,
    de_ranking: 1,
    piotroski: 9,
    piotroski_rank: 3,
    piotroski_score: 0.78,
    daily_filter_score: 16.0,
    sales_growth: "[8.38, 6.86, 1.86, 4.69]",
    sales_rank: "[2, 3, 4, 3]",
    sales_score: 0.42,
    sales_filter_score: 2.0,
    profit_growth: "[-16.0, -8.0, 26.0, 31.0]",
    profit_rank: "[4, 4, 3, 3]",
    profit_score: 0.11,
    profit_filter_score: 0.5,
    roe_10y: 17.0,
    roe_5y: 15.0,
    roe_3y: 18.0,
    roe_1y: 25.0,
    roe_rank_10y: 1,
    roe_rank_5y: 1,
    roe_rank_3y: 1,
    roe_rank_1y: 1,
    score: 0.45,
    filter_count: 2,
    total_ranks: 4,
    last_updated: "2025-03-14 10:10:45",
    Total_Filter_Score: 20.5,
    sum_score: 0.59,
    final_score: 14.44,
    target_price: 33401.69,
    Indicator: "Buy/Hold",
    SellPrice: 24946.66,
  },
  {
    company_name: "63 Moons Tech.",
    current_market_price: 723.0,
    company_screener: "https://www.screener.in/company/63MOONS/consolidated/",
    median_pe: 15.0,
    pe: 29.3,
    company_symbol: "526881",
    company_peers:
      '[{"company_name": "Accelya Solution", "company_screener": "https://www.screener.in/company/ACCELYA/consolidated/"}, {"company_name": "Airan", "company_screener": "https://www.screener.in/company/AIRAN/consolidated/"}, {"company_name": "All E Tech", "company_screener": "https://www.screener.in/company/ALLETEC/consolidated/"}, {"company_name": "AXISCADES Tech.", "company_screener": "https://www.screener.in/company/AXISCADES/consolidated/"}, {"company_name": "Birlasoft Ltd", "company_screener": "https://www.screener.in/company/BSOFT/consolidated/"}, {"company_name": "BLS E-Services", "company_screener": "https://www.screener.in/company/BLSE/consolidated/"}, {"company_name": "BLS Internat.", "company_screener": "https://www.screener.in/company/BLS/consolidated/"}, {"company_name": "C.E. Info System", "company_screener": "https://www.screener.in/company/MAPMYINDIA/consolidated/"}, {"company_name": "Coforge", "company_screener": "https://www.screener.in/company/COFORGE/consolidated/"}, {"company_name": "Cybertech Sys.", "company_screener": "https://www.screener.in/company/CYBERTECH/consolidated/"}, {"company_name": "Dynacons Sys.", "company_screener": "https://www.screener.in/company/DSSL/"}, {"company_name": "eClerx Services", "company_screener": "https://www.screener.in/company/ECLERX/consolidated/"}, {"company_name": "Firstsour.Solu.", "company_screener": "https://www.screener.in/company/FSL/consolidated/"}, {"company_name": "Hexaware Tech.", "company_screener": "https://www.screener.in/company/HEXT/consolidated/"}, {"company_name": "Hinduja Global", "company_screener": "https://www.screener.in/company/HGS/consolidated/"}, {"company_name": "Infibeam Avenues", "company_screener": "https://www.screener.in/company/INFIBEAM/consolidated/"}, {"company_name": "InfoBeans Tech.", "company_screener": "https://www.screener.in/company/INFOBEAN/consolidated/"}, {"company_name": "Innovana Think.", "company_screener": "https://www.screener.in/company/INNOVANA/consolidated/"}, {"company_name": "Intellect Design", "company_screener": "https://www.screener.in/company/INTELLECT/consolidated/"}, {"company_name": "Inventurus Knowl", "company_screener": "https://www.screener.in/company/IKS/consolidated/"}, {"company_name": "IRIS Business", "company_screener": "https://www.screener.in/company/IRIS/consolidated/"}, {"company_name": "KPIT Technologi.", "company_screener": "https://www.screener.in/company/KPITTECH/consolidated/"}, {"company_name": "Magellanic Cloud", "company_screener": "https://www.screener.in/company/MCLOUD/consolidated/"}, {"company_name": "Mindteck (India)", "company_screener": "https://www.screener.in/company/MINDTECK/consolidated/"}, {"company_name": "Network People", "company_screener": "https://www.screener.in/company/NPST/consolidated/"}, {"company_name": "Newgen Software", "company_screener": "https://www.screener.in/company/NEWGEN/"}, {"company_name": "Nucleus Soft.", "company_screener": "https://www.screener.in/company/NUCLEUS/consolidated/"}, {"company_name": "One Point One", "company_screener": "https://www.screener.in/company/ONEPOINT/consolidated/"}, {"company_name": "Onward Technolog", "company_screener": "https://www.screener.in/company/ONWARDTEC/consolidated/"}, {"company_name": "Oracle Fin.Serv.", "company_screener": "https://www.screener.in/company/OFSS/consolidated/"}, {"company_name": "Orient", "company_screener": "https://www.screener.in/company/ORIENTTECH/"}, {"company_name": "PB Fintech.", "company_screener": "https://www.screener.in/company/POLICYBZR/consolidated/"}, {"company_name": "Quick Heal Tech", "company_screener": "https://www.screener.in/company/QUICKHEAL/consolidated/"}, {"company_name": "Rategain Travel", "company_screener": "https://www.screener.in/company/RATEGAIN/consolidated/"}, {"company_name": "Silver Touch", "company_screener": "https://www.screener.in/company/SILVERTUC/consolidated/"}, {"company_name": "Tanla Platforms", "company_screener": "https://www.screener.in/company/TANLA/consolidated/"}, {"company_name": "Tata Elxsi", "company_screener": "https://www.screener.in/company/TATAELXSI/"}, {"company_name": "Vakrangee", "company_screener": "https://www.screener.in/company/VAKRANGEE/consolidated/"}, {"company_name": "Zensar Tech.", "company_screener": "https://www.screener.in/company/ZENSARTECH/consolidated/"}, {"company_name": "ABM Knowledge", "company_screener": "https://www.screener.in/company/531161/consolidated/"}, {"company_name": "Ceinsys Tech", "company_screener": "https://www.screener.in/company/538734/consolidated/"}, {"company_name": "Softsol India", "company_screener": "https://www.screener.in/company/532344/"}, {"company_name": "Technvision Ven.", "company_screener": "https://www.screener.in/company/501421/consolidated/"}]',
    sector: "IT - Software",
    industry: "Computers - Software - Medium / Small",
    pe_score: 0.01,
    peg_score: 0.33,
    peg_ranking: 20,
    de_score: 1.0,
    de_ranking: 1,
    piotroski: 8,
    piotroski_rank: 12,
    piotroski_score: 0.76,
    daily_filter_score: 12.0,
    sales_growth: "[-91.0, -94.0, -66.0, -66.0]",
    sales_rank: "[43, 42, 42, 41]",
    sales_score: 0.01,
    sales_filter_score: 0.5,
    profit_growth: "[-124.0, -131.0, -123.0, 144.0]",
    profit_rank: "[43, 41, 43, 8]",
    profit_score: 0.03,
    profit_filter_score: 0.5,
    roe_10y: -1.0,
    roe_5y: 0.0,
    roe_3y: 1.0,
    roe_1y: 6.0,
    roe_rank_10y: 25,
    roe_rank_5y: 38,
    roe_rank_3y: 41,
    roe_rank_1y: 37,
    score: 0.0,
    filter_count: 0,
    total_ranks: 44,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 13.0,
    sum_score: 0.29,
    final_score: 4.53,
    target_price: null,
    Indicator: "Sell",
    SellPrice: null,
  },
  {
    company_name: "A B B",
    current_market_price: 5120.0,
    company_screener: "https://www.screener.in/company/ABB/",
    median_pe: 102.9,
    pe: 57.9,
    company_symbol: "ABB",
    company_peers:
      '[{"company_name": "Alpex Solar", "company_screener": "https://www.screener.in/company/ALPEXSOLAR/consolidated/"}, {"company_name": "B H E L", "company_screener": "https://www.screener.in/company/BHEL/consolidated/"}, {"company_name": "Bharat Bijlee", "company_screener": "https://www.screener.in/company/BBL/"}, {"company_name": "CG Power & Ind", "company_screener": "https://www.screener.in/company/CGPOWER/consolidated/"}, {"company_name": "Exicom Tele-Sys.", "company_screener": "https://www.screener.in/company/EXICOM/consolidated/"}, {"company_name": "Focus Lighting", "company_screener": "https://www.screener.in/company/FOCUS/consolidated/"}, {"company_name": "Hitachi Energy", "company_screener": "https://www.screener.in/company/POWERINDIA/"}, {"company_name": "HPL Electric", "company_screener": "https://www.screener.in/company/HPL/consolidated/"}, {"company_name": "Igarashi Motors", "company_screener": "https://www.screener.in/company/IGARASHI/"}, {"company_name": "Indo Tech.Trans.", "company_screener": "https://www.screener.in/company/INDOTECH/"}, {"company_name": "Kirl. Electric", "company_screener": "https://www.screener.in/company/KECL/consolidated/"}, {"company_name": "Power & Instrum.", "company_screener": "https://www.screener.in/company/PIGL/"}, {"company_name": "Rishabh Instrum.", "company_screener": "https://www.screener.in/company/RISHABH/consolidated/"}, {"company_name": "Salzer Electron.", "company_screener": "https://www.screener.in/company/SALZERELEC/"}, {"company_name": "Siemens", "company_screener": "https://www.screener.in/company/SIEMENS/consolidated/"}, {"company_name": "Suzlon Energy", "company_screener": "https://www.screener.in/company/SUZLON/consolidated/"}, {"company_name": "Swelect Energy", "company_screener": "https://www.screener.in/company/SWELECTES/consolidated/"}, {"company_name": "T R I L", "company_screener": "https://www.screener.in/company/TARIL/consolidated/"}, {"company_name": "TD Power Systems", "company_screener": "https://www.screener.in/company/TDPOWERSYS/consolidated/"}, {"company_name": "Triveni Turbine", "company_screener": "https://www.screener.in/company/TRITURBINE/consolidated/"}, {"company_name": "Ujaas Energy", "company_screener": "https://www.screener.in/company/UEL/"}, {"company_name": "V-Guard Industri", "company_screener": "https://www.screener.in/company/VGUARD/"}, {"company_name": "Volt.Transform.", "company_screener": "https://www.screener.in/company/VOLTAMP/"}, {"company_name": "Waaree Energies", "company_screener": "https://www.screener.in/company/WAAREEENER/consolidated/"}, {"company_name": "Websol Energy", "company_screener": "https://www.screener.in/company/WEBELSOLAR/"}, {"company_name": "Artemis Electri.", "company_screener": "https://www.screener.in/company/542670/"}, {"company_name": "High Energy Bat.", "company_screener": "https://www.screener.in/company/504176/"}, {"company_name": "Hind.Urban Infra", "company_screener": "https://www.screener.in/company/539984/consolidated/"}, {"company_name": "Modern Insulator", "company_screener": "https://www.screener.in/company/515008/"}, {"company_name": "Shilchar Tech.", "company_screener": "https://www.screener.in/company/531201/"}, {"company_name": "Taylormade Renew", "company_screener": "https://www.screener.in/company/541228/"}]',
    sector: "Capital Goods - Electrical Equipment",
    industry: "Electric Equipment",
    pe_score: 1.0,
    peg_score: 0.45,
    peg_ranking: 12,
    de_score: 0.96,
    de_ranking: 4,
    piotroski: 8,
    piotroski_rank: 10,
    piotroski_score: 0.75,
    daily_filter_score: 16.0,
    sales_growth: "[22.03, 5.16, 12.84, 27.75]",
    sales_rank: "[18, 19, 19, 5]",
    sales_score: 0.32,
    sales_filter_score: 2.5,
    profit_growth: "[54.0, 22.0, 50.0, 87.0]",
    profit_rank: "[12, 17, 14, 7]",
    profit_score: 0.3,
    profit_filter_score: 2.5,
    roe_10y: 16.0,
    roe_5y: 19.0,
    roe_3y: 24.0,
    roe_1y: 29.0,
    roe_rank_10y: 5,
    roe_rank_5y: 5,
    roe_rank_3y: 6,
    roe_rank_1y: 6,
    score: 0.9,
    filter_count: 4,
    total_ranks: 32,
    last_updated: "2025-03-14 10:10:45",
    Total_Filter_Score: 25.0,
    sum_score: 0.71,
    final_score: 21.44,
    target_price: 7109.64,
    Indicator: "Buy/Hold",
    SellPrice: 4125.18,
  },
  {
    company_name: "A B Real Estate",
    current_market_price: 1898.0,
    company_screener: "https://www.screener.in/company/ABREL/consolidated/",
    median_pe: 78.3,
    pe: 1162.0,
    company_symbol: "ABREL",
    company_peers:
      '[{"company_name": "Andhra Paper", "company_screener": "https://www.screener.in/company/ANDHRAPAP/"}, {"company_name": "Emami Paper", "company_screener": "https://www.screener.in/company/EMAMIPAP/"}, {"company_name": "Genus Paper & Bo", "company_screener": "https://www.screener.in/company/GENUSPAPER/consolidated/"}, {"company_name": "JK Paper", "company_screener": "https://www.screener.in/company/JKPAPER/consolidated/"}, {"company_name": "Kuantum Papers", "company_screener": "https://www.screener.in/company/KUANTUM/"}, {"company_name": "Pudumjee Paper", "company_screener": "https://www.screener.in/company/PDMJEPAPER/"}, {"company_name": "Satia Industries", "company_screener": "https://www.screener.in/company/SATIA/"}, {"company_name": "Seshasayee Paper", "company_screener": "https://www.screener.in/company/SESHAPAPER/"}, {"company_name": "West Coast Paper", "company_screener": "https://www.screener.in/company/WSTCSTPAPR/consolidated/"}]',
    sector: "Paper",
    industry: "Paper",
    pe_score: 0.01,
    peg_score: 0.0,
    peg_ranking: 1,
    de_score: -0.1,
    de_ranking: 10,
    piotroski: 4,
    piotroski_rank: 10,
    piotroski_score: 0.04,
    daily_filter_score: 0.0,
    sales_growth: "[-10.61, 30.67, 28.48, 71.71]",
    sales_rank: "[7, 1, 1, 1]",
    sales_score: 0.49,
    sales_filter_score: 0.0,
    profit_growth: "[-135.0, 217.0, -72.0, -58.0]",
    profit_rank: "[10, 1, 9, 8]",
    profit_score: 0.14,
    profit_filter_score: 0.0,
    roe_10y: -1.0,
    roe_5y: 4.0,
    roe_3y: 3.0,
    roe_1y: 1.0,
    roe_rank_10y: 7,
    roe_rank_5y: 9,
    roe_rank_3y: 9,
    roe_rank_1y: 9,
    score: 0.1,
    filter_count: 1,
    total_ranks: 10,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 1.0,
    sum_score: 0.12,
    final_score: 0.14,
    target_price: null,
    Indicator: "Sell",
    SellPrice: null,
  },
  {
    company_name: "A K Spintex",
    current_market_price: 944.0,
    company_screener: "https://www.screener.in/company/539300/",
    median_pe: 9.7,
    pe: 71.3,
    company_symbol: "539300",
    company_peers:
      '[{"company_name": "Alok Industries", "company_screener": "https://www.screener.in/company/ALOKINDS/consolidated/"}, {"company_name": "AYM Syntex", "company_screener": "https://www.screener.in/company/AYMSYNTEX/"}, {"company_name": "Ganesha Ecosphe.", "company_screener": "https://www.screener.in/company/GANECOS/consolidated/"}, {"company_name": "Raj Rayon Inds.", "company_screener": "https://www.screener.in/company/RAJRILTD/"}, {"company_name": "Siyaram Silk", "company_screener": "https://www.screener.in/company/SIYSIL/"}, {"company_name": "Jaybharat Text", "company_screener": "https://www.screener.in/company/512233/"}, {"company_name": "LS Industries", "company_screener": "https://www.screener.in/company/514446/"}]',
    sector: "Textiles",
    industry: "Textiles - Processing",
    pe_score: 0.01,
    peg_score: 0.03,
    peg_ranking: 5,
    de_score: 0.77,
    de_ranking: 2,
    piotroski: 7,
    piotroski_rank: 2,
    piotroski_score: 0.88,
    daily_filter_score: 7.0,
    sales_growth: "[-6.58, -4.83, -19.99, -5.51]",
    sales_rank: "[5, 5, 5, 5]",
    sales_score: 0.21,
    sales_filter_score: 1.0,
    profit_growth: "[-20.0, 11.98, -78.03, 36.36]",
    profit_rank: "[7, 3, 5, 4]",
    profit_score: 0.15,
    profit_filter_score: 0.0,
    roe_10y: 14.0,
    roe_5y: 16.0,
    roe_3y: 21.0,
    roe_1y: 24.0,
    roe_rank_10y: 2,
    roe_rank_5y: 1,
    roe_rank_3y: 1,
    roe_rank_1y: 1,
    score: 0.5,
    filter_count: 3,
    total_ranks: 8,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 11.0,
    sum_score: 0.37,
    final_score: 4.92,
    target_price: null,
    Indicator: "Sell",
    SellPrice: null,
  },
  {
    company_name: "A-1",
    current_market_price: 456.0,
    company_screener: "https://www.screener.in/company/542012/",
    median_pe: 76.6,
    pe: 147.0,
    company_symbol: "542012",
    company_peers:
      '[{"company_name": "Adani Enterp.", "company_screener": "https://www.screener.in/company/ADANIENT/consolidated/"}, {"company_name": "Aegis Logistics", "company_screener": "https://www.screener.in/company/AEGISLOG/consolidated/"}, {"company_name": "Cello World", "company_screener": "https://www.screener.in/company/CELLO/consolidated/"}, {"company_name": "D-Link India", "company_screener": "https://www.screener.in/company/DLINKINDIA/"}, {"company_name": "Hexa Tradex", "company_screener": "https://www.screener.in/company/HEXATRADEX/consolidated/"}, {"company_name": "Honasa Consumer", "company_screener": "https://www.screener.in/company/HONASA/"}, {"company_name": "Kamdhenu Venture", "company_screener": "https://www.screener.in/company/KAMOPAINTS/consolidated/"}, {"company_name": "Kothari Products", "company_screener": "https://www.screener.in/company/KOTHARIPRO/consolidated/"}, {"company_name": "Manaksia", "company_screener": "https://www.screener.in/company/MANAKSIA/consolidated/"}, {"company_name": "Mangalam Global", "company_screener": "https://www.screener.in/company/MGEL/"}, {"company_name": "MMTC", "company_screener": "https://www.screener.in/company/MMTC/consolidated/"}, {"company_name": "Optiemus Infra.", "company_screener": "https://www.screener.in/company/OPTIEMUS/consolidated/"}, {"company_name": "Redington", "company_screener": "https://www.screener.in/company/REDINGTON/consolidated/"}, {"company_name": "Saraswati", "company_screener": "https://www.screener.in/company/SSDL/"}, {"company_name": "Sreeleathers", "company_screener": "https://www.screener.in/company/SREEL/"}, {"company_name": "Uniphos Enter.", "company_screener": "https://www.screener.in/company/UNIENTER/"}, {"company_name": "Vishal Mega Mart", "company_screener": "https://www.screener.in/company/VMM/consolidated/"}, {"company_name": "Black Rose Indus", "company_screener": "https://www.screener.in/company/514183/consolidated/"}, {"company_name": "Hampton Sky", "company_screener": "https://www.screener.in/company/526407/consolidated/"}, {"company_name": "Khazanchi Jewell", "company_screener": "https://www.screener.in/company/543953/"}, {"company_name": "Riddhi Siddhi Gl", "company_screener": "https://www.screener.in/company/524480/consolidated/"}, {"company_name": "Veritas (India)", "company_screener": "https://www.screener.in/company/512229/consolidated/"}, {"company_name": "Vintron Info.", "company_screener": "https://www.screener.in/company/517393/"}]',
    sector: "Trading",
    industry: "Trading",
    pe_score: 0.01,
    peg_score: 0.0,
    peg_ranking: 1,
    de_score: 0.52,
    de_ranking: 19,
    piotroski: 6,
    piotroski_rank: 21,
    piotroski_score: 0.33,
    daily_filter_score: 2.0,
    sales_growth: "[83.0, 65.0, 19.0, -16.0]",
    sales_rank: "[3, 5, 5, 15]",
    sales_score: 0.48,
    sales_filter_score: 5.5,
    profit_growth: "[376.0, 2525.0, 367.0, -30.0]",
    profit_rank: "[2, 3, 3, 18]",
    profit_score: 0.33,
    profit_filter_score: 4.5,
    roe_10y: -1.0,
    roe_5y: 8.0,
    roe_3y: 8.0,
    roe_1y: 3.0,
    roe_rank_10y: 13,
    roe_rank_5y: 7,
    roe_rank_3y: 10,
    roe_rank_1y: 19,
    score: 0.2,
    filter_count: 2,
    total_ranks: 24,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 14.0,
    sum_score: 0.28,
    final_score: 4.63,
    target_price: null,
    Indicator: "Sell",
    SellPrice: null,
  },
  {
    company_name: "Aarti Drugs",
    current_market_price: 356.0,
    company_screener: "https://www.screener.in/company/AARTIDRUGS/",
    median_pe: 26.4,
    pe: 24.8,
    company_symbol: "AARTIDRUGS",
    company_peers:
      '[{"company_name": "Ami Organics", "company_screener": "https://www.screener.in/company/AMIORG/consolidated/"}, {"company_name": "Anuh Pharma", "company_screener": "https://www.screener.in/company/ANUHPHR/"}, {"company_name": "Divi\'s Lab.", "company_screener": "https://www.screener.in/company/DIVISLAB/consolidated/"}, {"company_name": "Guj. Themis Bio.", "company_screener": "https://www.screener.in/company/GUJTHEM/"}, {"company_name": "Hikal", "company_screener": "https://www.screener.in/company/HIKAL/consolidated/"}, {"company_name": "Jubilant Pharmo", "company_screener": "https://www.screener.in/company/JUBLPHARMA/consolidated/"}, {"company_name": "Neuland Labs.", "company_screener": "https://www.screener.in/company/NEULANDLAB/consolidated/"}, {"company_name": "NGL Fine Chem", "company_screener": "https://www.screener.in/company/NGLFINE/consolidated/"}, {"company_name": "SMS Pharma.", "company_screener": "https://www.screener.in/company/SMSPHARMA/"}]',
    sector: "Pharmaceuticals",
    industry: "Pharmaceuticals - Indian - Bulk Drugs",
    pe_score: 0.19,
    peg_score: 0.39,
    peg_ranking: 7,
    de_score: 0.55,
    de_ranking: 7,
    piotroski: 7,
    piotroski_rank: 6,
    piotroski_score: 0.65,
    daily_filter_score: 12.0,
    sales_growth: "[-4.4, -5.96, -16.68, -19.66]",
    sales_rank: "[9, 8, 9, 10]",
    sales_score: 0.18,
    sales_filter_score: 1.0,
    profit_growth: "[21.85, -12.12, -31.94, -32.03]",
    profit_rank: "[5, 8, 10, 10]",
    profit_score: 0.32,
    profit_filter_score: 2.5,
    roe_10y: 20.0,
    roe_5y: 20.0,
    roe_3y: 16.0,
    roe_1y: 12.0,
    roe_rank_10y: 1,
    roe_rank_5y: 3,
    roe_rank_3y: 5,
    roe_rank_1y: 5,
    score: 0.3,
    filter_count: 2,
    total_ranks: 10,
    last_updated: "2025-03-14 10:10:46",
    Total_Filter_Score: 17.5,
    sum_score: 0.39,
    final_score: 8.27,
    target_price: 367.48,
    Indicator: "Buy/Hold",
    SellPrice: 350.26,
  },
];
